### PR TITLE
update: Move to version v3.12

### PR DESCRIPTION
**Pull request by nashif**
Update to major version v3.12.

The most significant enhancement is the addition of real-time data acquisition
via UAR­T or TCP/IP. Any system with UART or TCP/IP connection, typically
Ethernet, can now be monitored and verified.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
Approving, although I'd really prefer we standardized the commit message to the format that describes the origin of the software:

https://docs.zephyrproject.org/latest/contribute/index.html#identifying-contribution-origin

**Comment by Vge0rge** [comment]
@nashif @carlescufi  Do you have an estimation on when this will be merged?

**Comment by nashif** [comment]
need to rebase and retest first...

**Comment by carlescufi** [comment]
@nordic-krch please take a look

**Comment by nashif** [comment]
obsolete

**Pull request closed without merging**
